
SCREEN_WIDTH = 1800
SCREEN_HEIGHT = 900

BOAR_MIN_RADIUS = 20
BOAR_KINDS = 3
BOAR_SPAWN_RATE = 1  # seconds
BOAR_MID_RADIUS = BOAR_MIN_RADIUS * 2
BOAR_MAX_RADIUS = BOAR_MIN_RADIUS * 3

PLAYER_RADIUS = 40
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.25

BACON_BIT_RADIUS = 1
